### ISSUE TITLE
verify gmail contacts import/export

### ISSUE THREAD

**Issue by mattkiefer** [bettergov/foiamail#42]
make sure that none of the new contacts are  

and add this to the user manual

**Comment by phjudge** [comment]
Manual contacts import added to:
* technical docs in da81603b8be9bc9e5223ab64bae0e5f6be2a8bc4
* main readme in 07cc5a8f89a58ad86ae84a6b602d31a63a5a7669

**Comment by mattkiefer** [comment]
contacts import/export handled via UI at this time

feature roadmap may revisit contact import via google sheets picker
